### ISSUE TITLE
Font is different

### ISSUE THREAD

**Issue by mzaini30** [LordDashMe/github-contribution-stats#2]
**In Github profile**

![Screenshot_2020-07-24-12-55-45-54](https://user-images.githubusercontent.com/7939342/88361881-26126f00-cdad-11ea-97fe-99ff19746814.png)

**Original SVG**

![Screenshot_2020-07-24-12-56-01-88](https://user-images.githubusercontent.com/7939342/88361905-39253f00-cdad-11ea-92ae-d070031924c1.png)

**Comment by LordDashMe** [comment]
Good catch @mzaini30 ! because of github proxy [Github Como Proxy Service](https://github.blog/2010-11-13-sidejack-prevention-phase-3-ssl-proxied-assets/) we are limited to the default fonts of devices only and external resources like fonts will be blocked by this setup. Can I know the details of device you are using here? :smile:

**Comment by mzaini30** [comment]
@LordDashMe 
Device: Realme C2
Browser: Chrome
